export const json = {
  title: 'TryBookinz',
  description:
    'Please take look at the survey title and logo. Test the settings on the right panel ->',
  logo: 'https://surveyjs.io/favicon.ico',
  logoWidth: 60,
  logoHeight: 60,
  questions: [
    {
      name: 'email',
      type: 'text',
      title: 'Customer ID',
      inputType: 'email',
      defaultValue: 'olotintemitope@gmail.com',
      isRequired: true,
      readOnly: true,
    },
    {
      name: 'wifi',
      type: 'rating',
      title: 'How satisfied are you with the Wifi',
      minRateDescription: 'Not Satisfied',
      maxRateDescription: 'Completely satisfied',
      displayMode: 'buttons',
    },
    {
      name: 'air-conditioning',
      type: 'rating',
      title: 'How satisfied are you with the Air Conditioning',
      minRateDescription: 'Not Satisfied',
      maxRateDescription: 'Completely satisfied',
      displayMode: 'buttons',
    },
    {
      name: 'heating',
      type: 'rating',
      title: 'How satisfied are you with the Heating',
      minRateDescription: 'Not Satisfied',
      maxRateDescription: 'Completely satisfied',
      displayMode: 'buttons',
    },
    {
      name: 'standing-desks',
      type: 'rating',
      title: 'How satisfied are you with the Standing Desks',
      minRateDescription: 'Not Satisfied',
      maxRateDescription: 'Completely satisfied',
      displayMode: 'buttons',
    },
    {
      name: 'ergonomic-chairs',
      type: 'rating',
      title: 'How satisfied are you with the Ergonomic Chairs',
      minRateDescription: 'Not Satisfied',
      maxRateDescription: 'Completely satisfied',
      displayMode: 'buttons',
    },
    {
      name: 'beanbags',
      type: 'rating',
      title: 'How satisfied are you with the Beanbags',
      minRateDescription: 'Not Satisfied',
      maxRateDescription: 'Completely satisfied',
      displayMode: 'buttons',
    },
    {
      name: 'printer',
      type: 'rating',
      title: 'How satisfied are you with the Printer',
      minRateDescription: 'Not Satisfied',
      maxRateDescription: 'Completely satisfied',
      displayMode: 'buttons',
    },
    {
      type: 'rating',
      name: 'overall-rating',
      title: 'How will you rate your overall experience?',
      minRateDescription: 'Not Satisfied',
      maxRateDescription: 'Completely satisfied',
      displayMode: 'buttons',
    },
    {
      type: 'comment',
      name: 'suggestions',
      title: 'How satisfied are you with this space? Drop a review',
    },
  ],
}
